name: "rnaquast"
description: Assess the quality of an RNAseq assembly with or without a reference genome
keywords:
  - rna assembly
  - rnaseq
  - de novo
  - quality control
tools:
  - "rnaquast":
      description: "rnaQUAST is a tool for evaluating RNA-Seq assemblies using reference genome and gene database. In addition, rnaQUAST is also capable of estimating gene database coverage by raw reads and de novo quality assessment using third-party software."
      homepage: "https://cab.spbu.ru/software/rnaquast/"
      documentation: "http://cab.spbu.ru/files/rnaquast/release2.2.2/manual.html"
      tool_dev_url: "https://github.com/ablab/rnaquast"
      doi: "10.1093/bioinformatics/btw218"
      licence: "['GPL v2']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - assembly:
      type: file
      description: fasta file
      pattern: "*.{fasta,fa}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - rnaquast_dir:
      type: directory
      description: Summary statistics output directory
      pattern: "comparison_output/*"

authors:
  - "timslittle"
